//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE310.Tools.CodeMaker {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IE310.Tools.CodeMaker.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 	/// &lt;summary&gt;
        ///    /// ClassSummary
        ///    /// &lt;/summary&gt; 的本地化字符串。
        /// </summary>
        internal static string ClassSummary {
            get {
                return ResourceManager.GetString("ClassSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using IE310.Framework.Core;
        ///using IE310.Framework.Core.Util;
        ///using IE310.Core.DB;
        ///using IE310.Core.Utils;
        ///refrenceUsingList
        ///
        ///namespace namespaceName
        ///{
        ///    public  partial class DatabaseObjectService : SingletonService
        ///    {
        ///        public static DatabaseObjectService Current
        ///        {
        ///            get
        ///            {
        ///                return ClientServiceFactory.GetRemotingService(typeof(DatabaseObjectService)) as DatabaseObjectS [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ClientService {
            get {
                return ResourceManager.GetString("ClientService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Text;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Reflection;
        ///using  IE310.Core.Utils;
        ///using IE310.Core.DB;
        ///refrenceUsingList
        ///
        ///
        ///namespace namespaceName
        ///{
        ///	[Serializable]
        ///    public partial class DatabaseObjectEntities : I3DataObjectEntities&lt;DatabaseObjectEntity&gt;
        ///    {
        ///        public DatabaseObjectEntities()
        ///            :base()
        ///        {
        ///        }
        ///
        ///        public DatabaseObjectEntities(DatabaseObjectEntity[] entities)
        ///            [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 package {packageName};
        ///
        ///import java.lang.reflect.InvocationTargetException;
        ///{importList}
        ///
        ///public interface I{entityName}Service
        ///{
        ///	/**
        ///	 * 返回对象或null
        ///	 */
        ///	public {entityName} get({idColDataType} id) throws Exception;
        ///	
        ///	/**
        ///	 * 返回对象或null  注意，需要数据表中有code字段才能正确调用
        ///	 */
        ///	public {entityName} getByCode(String code) throws Exception;
        ///	
        ///	/**
        ///	 * 成功返回1，失败返回0
        ///	 */
        ///	public boolean delete({idColDataType} id) throws Exception;
        ///
        ///	
        ///	/**
        ///	 * 
        ///	 */
        ///	public boolean deleteByParam({entityName}Param pa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IServiceForJava {
            get {
                return ResourceManager.GetString("IServiceForJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 package {packageName};
        ///
        ///import java.io.UnsupportedEncodingException;
        ///import java.util.UUID;
        ///import org.springframework.beans.factory.BeanFactory;
        ///import org.springframework.beans.factory.annotation.Autowired;
        ///import org.springframework.context.ApplicationContext;
        ///import org.springframework.context.support.ClassPathXmlApplicationContext;
        ///import com.google.common.reflect.TypeToken;
        ///import com.google.gson.Gson;
        ///import org.apache.log4j.Logger;
        ///{importList}
        ///
        ///public class {entityName}Service extends  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JsonServiceForJava {
            get {
                return ResourceManager.GetString("JsonServiceForJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///function jssAdd{entityName}(item, invokeServiceSuccess) {
        ///    var itemJson = JSON.stringify(item);
        ///    var data = {};
        ///    data.itemJson = encodeURIComponent(itemJson);
        ///
        ///    beginInvokeJsonService(&quot;/{tableNameEx2}Service{suffixJss}&quot;, &quot;add&quot;, data, invokeServiceSuccess, invokeServiceError);
        ///}
        ///
        ///
        ///function jssUpdate{entityName}(item, invokeServiceSuccess) {
        ///    var itemJson = JSON.stringify(item);
        ///    var data = {};
        ///    data.itemJson = encodeURIComponent(itemJson);
        ///
        ///    beginInvokeJsonService(&quot;/{t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JssFileForH5 {
            get {
                return ResourceManager.GetString("JssFileForH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using IE310.Core.DB;
        ///using IE310.Core.Utils;
        ///refrenceUsingList
        ///
        ///namespace namespaceName
        ///{
        ///	/// &lt;summary&gt;
        ///    /// DatabaseObject业务管理类
        ///    /// &lt;/summary&gt;
        ///public static  partial class DatabaseObjectManager
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 根据ID获取实例
        ///        /// &lt;/summary&gt;
        ///        public static DatabaseObjectEntity Get(string id)
        ///        {
        ///            return DatabaseObjectHelper.Get(id, null);
        ///        }
        ///
        ///        /// &lt;summary&gt;
        ///        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using IE310.Core.DB;
        ///using IE310.Core.Utils;
        ///refrenceUsingList
        ///
        ///namespace namespaceName
        ///{
        ///	/// &lt;summary&gt;
        ///    /// DatabaseObject业务管理类
        ///    /// &lt;/summary&gt;
        ///public static  partial class DatabaseObjectManager
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 根据ID获取实例
        ///        /// &lt;/summary&gt;
        ///        public static DatabaseObjectEntity Get(int id)
        ///        {
        ///            return DatabaseObjectHelper.Get(id, null);
        ///        }
        ///
        ///        /// &lt;summary&gt;
        ///        /// 保存 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ManagerAutoInt {
            get {
                return ResourceManager.GetString("ManagerAutoInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*   说明：自动生成的XXXXMapper文件
        ///
        ///Exists(tx, id)                根据id判断数据是否存在
        ///GetByCode(tx, code)  根据code获取，需要有code字段
        ///
        ///Get(tx, id)                                                  根据id获取
        ///GetFirst(tx, whereStr, orderStr, args...)   获取第1条数据
        ///
        ///Gets(tx, pageIndex, rowsInPage, whereStr, orderStr, args...) []   获取多条数据、pageIndex从1开始、whereStr、orderStr可以为空，不要where、order by部分
        ///Getss(tx, pageIndex, rowsInPage, sqlStr, args...)                     []   获取多条数据、需要完整的sql语句、pageIndex从1开始
        ///
        ///GetTops(tx, top, whereStr, orderS [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MapperForGo {
            get {
                return ResourceManager.GetString("MapperForGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 package {packageName};
        ///
        ///import org.apache.ibatis.annotations.Delete;
        ///import org.apache.ibatis.annotations.Insert;
        ///import org.apache.ibatis.annotations.Options;
        ///import org.apache.ibatis.annotations.Select;
        ///import org.apache.ibatis.annotations.Update;
        ///import org.apache.ibatis.annotations.SelectProvider;
        ///import org.apache.ibatis.annotations.UpdateProvider;
        ///import org.apache.ibatis.annotations.DeleteProvider;
        ///import org.apache.ibatis.annotations.Param;
        ///import java.util.*;
        ///{importList}
        ///
        ///{myBatisMap [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MapperForJava {
            get {
                return ResourceManager.GetString("MapperForJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		/// &lt;summary&gt;
        ///		/// PropertySummary
        ///		/// &lt;/summary&gt; 的本地化字符串。
        /// </summary>
        internal static string PropertySummary {
            get {
                return ResourceManager.GetString("PropertySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using IE310.Framework.Core;
        ///using IE310.Framework.Core.Util;
        ///using IE310.Core.DB;
        ///using IE310.Core.Utils;
        ///refrenceUsingList
        ///
        ///namespace namespaceName
        ///{
        ///    public  partial class DatabaseObjectService : SingletonService
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 根据ID获取实例
        ///        /// &lt;/summary&gt;
        ///        public DatabaseObjectEntity Get(string id)
        ///        {
        ///                return DatabaseObjectManager.Get(id);
        ///        }
        ///
        ///         [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ServerService {
            get {
                return ResourceManager.GetString("ServerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- - Copyright 1999-2011 Alibaba Group. - - Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); - you may not use this file except in compliance with the License. - You may obtain a copy 
        ///	of the License at - - http://www.apache.org/licenses/LICENSE-2.0 - - Unless required by applicable law or agreed to in writing, software - distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        ///	- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expre [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ServiceConsumerForJava {
            get {
                return ResourceManager.GetString("ServiceConsumerForJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 package service
        ///
        ///import (
        ///	&quot;math&quot;
        ///
        ///{importList}
        ///	{idIsStringDes1}&quot;github.com/ie310mu/ie310go/common/guid&quot;
        ///	&quot;github.com/ie310mu/ie310go/common/json&quot;
        ///	&quot;github.com/ie310mu/ie310go/common/paging&quot;
        ///	&quot;github.com/ie310mu/ie310go/route&quot;
        ///{customRefrence}
        ///)
        ///
        ///func init() {
        ///	route.Add(&amp;{entityName}Service{})
        ///}
        ///
        /////{entityName}Service 自动生成的代码
        /////默认生成get、getList、add、update、delete5个方法
        /////注意，以上方法使用非事务模式，如果需要使用事务，可在customContent中自行处理
        ///type {entityName}Service struct {
        ///	BaseLoginedService
        ///}
        ///
        /////Get ..
        ///func [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ServiceForGo {
            get {
                return ResourceManager.GetString("ServiceForGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 package {packageName};
        ///
        ///import java.lang.reflect.Method;
        ///import java.lang.reflect.InvocationTargetException;
        ///import org.apache.log4j.Logger;
        ///{importList}
        ///
        ///public class {entityName}ServiceImpl extends BaseService implements I{entityName}Service
        ///{
        ///	private static final Logger logger = Logger.getLogger({entityName}ServiceImpl.class);
        ///	
        ///	public {entityName} get({idColDataType} id)  throws Exception
        ///	{
        ///		{entityName}Mapper mapper = this.getReadonlyMapper({entityName}Mapper.class);
        ///		{entityName} it [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ServiceImplForJava {
            get {
                return ResourceManager.GetString("ServiceImplForJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- - Copyright 1999-2011 Alibaba Group. - - Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); - you may not use this file except in compliance with the License. - You may obtain a copy 
        ///	of the License at - - http://www.apache.org/licenses/LICENSE-2.0 - - Unless required by applicable law or agreed to in writing, software - distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        ///	- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expre [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ServiceProviderForJava {
            get {
                return ResourceManager.GetString("ServiceProviderForJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 package {packageName};
        ///
        ///import java.util.Map;
        ///{importList}
        ///
        ///public class {entityName}SqlProvider extends BaseSqlProvider
        ///{
        ///	public {entityName}SqlProvider()
        ///	{
        ///		this.tableName = &quot;{tableName}&quot;;
        ///	}
        ///
        ///
        ///
        ///{customContent}
        ///
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string SqlProviderForJava {
            get {
                return ResourceManager.GetString("SqlProviderForJava", resourceCulture);
            }
        }
    }
}
